### ISSUE TITLE
Remove async methods?

### ISSUE THREAD

**Issue by nellshamrell** [git-bom/gitbom-rs#36]
Hello all!

I have been experimenting with our async API methods over on [gitbom-rs-cli](https://github.com/nellshamrell/gitbom-rs-cli).

Most recent experiment: https://github.com/nellshamrell/gitbom-rs-cli/pull/21
Previous experiment: https://github.com/nellshamrell/gitbom-rs-cli/pull/18

As noted in the comments on the previous experiment, I'm not seeing a performance gain when using the async methods (in fact, there appears to be a performance penalty, though it is of course possible I'm blocking on something unintentionally). GitBOM is heavily dependent on many file reads and file writes and, as the tokio documentation states:

"Although it seems like Tokio would be useful for projects that simply need to read a lot of files, Tokio provides no advantage here compared to an ordinary threadpool. This is because operating systems generally do not provide asynchronous file APIs."

It's possible we could make use of [io_uring](https://en.wikipedia.org/wiki/Io_uring), there has been some experimental work done on this (including with tokio) but support for it is still not wide-spread. This would also only benefit us on Linux, not on Windows. It is possible there is some sort of library that would support async file operations on Windows, but then we would need to maintain two separate sets of functionality - one for Linux and one for Windows. This is not impossible, but it adds to complexity and increases the maintainership burden more than it needs to at this time (imo).

The work that was done to add the async methods was tremendously valuable - I know I learned a lot and I believe other maintainers did as well. However, I propose removing the async API calls at least for now, and leaving it the project which uses the library to decide how to implement performant use of it through threads, etc. We can always add this functionality back in should it become necessary.

**Comment by nellshamrell** [comment]
@yoshuawuyts, as one of the reviewers on [the PR which added this async functionality](https://github.com/git-bom/gitbom-rs/pull/17), I'm curious what you think too :)

**Comment by alilleybrinker** [comment]
I can say for my own part that removing async would certainly simplify the changes I’m interested in making, namely to make it optional to pass the length of the hashed material for a GitOid up-front. Expressing the equivalent Seek bound in an async context isn’t something I’ve figured out. That said, if there’s a way to do it for async I'm happy to learn.

**Comment by yoshuawuyts** [comment]
> @yoshuawuyts, as one of the reviewers on https://github.com/git-bom/gitbom-rs/pull/17, I'm curious what you think too :)

I recently authored a post on [the benefits I see of using async Rust](https://blog.yoshuawuyts.com/why-async-rust/): the ability to apply ad-hoc concurrency, use ad-hoc cancellation, and being able to combine the two to apply things like timeouts on arbitrary operations.    To me these properties generally seem like the clearest benefits for adopting async Rust, as implementing their counterparts in non-async Rust will generally require going through the OS to achieve similar results.

Being able to do those things does come with a meaningful tradeoff which is: complexity. Async Rust is harder to author, has fewer stdlib facilities, and is harder to debug. I'm on the Async Rust WG where we're trying to improve these things - but our progress is measured in years, meaning improvements will take a while longer.

Looking at the codebase here, it seems that the workload here is mostly batch-oriented. Files are read from disk, and then processed using hashing algorithms. Most async OS facilities are not (yet) optimized for disk IO, which makes sense that the non-async version would often run faster than the non-async variant. But this is indeed likely to change in the near(ish) future as `io_uring` becomes more commonplace. Because we're in this in-between state, I usually only check whether performance of a project is "good enough", and then leave it there.

To get back to the main question though; I think the question to ask here should be: _"Is having features such as ad-hoc concurrency and cancellation worth the added complexity of using async?"_ The answer to this will depend on your current maintainer's capacity and future plans for the project, which are not things I have insight into.

I hope this helps you evaluate whether async Rust is the right choice for this project!

**Comment by nellshamrell** [comment]
Thank you so much for the input, @yoshuawuyts! I personally do not think having the ad-hoc concurrency and cancellation is worth the added complexity at this time. This may change with wider adoption of io_uring (and an equivalent on Windows), but I would personally prefer to remove the async methods at this time. Again, this is not meant to diminish the quality or importance of that work - we learned a ton and I really appreciate @dpp's work in particular - but I believe it would be better for forward development of this library to remove it for now.

**Comment by nellshamrell** [comment]
Checked on this with @dpp and I'm proceeding forward with removing the async methods - pull request coming soon!
